# Generated by Django 5.2.4 on 2026-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Завершен')], default='open', max_length=6),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=124, unique=True),
        ),
    ]
